Description: >
  Create RDS - PostgreSQL DB.

Resources:
  PostgesDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      DBInstanceClass: db.t2.micro
      DBName: "demodb"
      Engine: postgres
      MasterUsername: postgres
      MasterUserPassword: "{{resolve:ssm-secure:ssbRDSmEcntl:1}}"
      PubliclyAccessible: True